const { GoogleGenAI, Modality } = require('@google/genai');
const dotenv = require('dotenv');
const fs = require('fs');
const path = require('path');

dotenv.config({ path: path.join(__dirname, '..', '.env') });

const apiKey = process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY || '';

async function testVoice() {
  console.log('Testing Gemini Podcast TTS voices...');
  const ai = new GoogleGenAI({
    apiKey,
    httpOptions: { headers: { 'User-Agent': 'aistudio-build' } },
  });

  try {
    const res1 = await ai.models.generateContent({
      model: 'gemini-2.0-flash',
      contents: [{ parts: [{ text: "Welcome back to the Deep Dive! Today we're checking out ActWise Live." }] }],
      config: {
        responseModalities: [Modality.AUDIO],
        speechConfig: {
          voiceConfig: { prebuiltVoiceConfig: { voiceName: 'Puck' } },
        },
      },
    });

    const b64_1 = res1.candidates?.[0]?.content?.parts?.[0]?.inlineData?.data;
    console.log('Host 1 (Puck) generated bytes:', b64_1 ? b64_1.length : 'none');

    const res2 = await ai.models.generateContent({
      model: 'gemini-2.0-flash',
      contents: [{ parts: [{ text: "That's right, Alex. This is an ambient voice AI built for NICE Actimize documentation." }] }],
      config: {
        responseModalities: [Modality.AUDIO],
        speechConfig: {
          voiceConfig: { prebuiltVoiceConfig: { voiceName: 'Aoede' } },
        },
      },
    });

    const b64_2 = res2.candidates?.[0]?.content?.parts?.[0]?.inlineData?.data;
    console.log('Host 2 (Aoede) generated bytes:', b64_2 ? b64_2.length : 'none');

    console.log('✅ Gemini Podcast TTS verified!');
  } catch (err) {
    console.error('TTS test notice:', err.message);
  }
}

testVoice();
